version: "3.7"

services:
  db:
    build: postgre-db
    image: postgre-db:latest
    container_name: "postgre-db"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passw0rd
      POSTGRES_DB: postgres
    volumes:
      - ./postgre-db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always