spring:
  liquibase:
    change-log: classpath:/liquibase/dbChangeLog.xml
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    ##    driver-class-name: org.h2.Driver
    ##    url: jdbc:h2:mem:test
    username: user
    password: passw0rd
#  h2:
#    console:
#      enabled: true
logging:
  level:
    liquibase: INFO